import ERC6358Protocol from "./ERC6358Protocol.cdc"

pub contract interface IERC6358Token {
    
    pub let flowChainID: UInt32;
    pub let contractName: String;

    // value is generated by `String.encodeHex(contract address: [UInt8])`
    pub let allowedMembers: {UInt32: String};

    pub fun getTransactionCount(pk: [UInt8]): UInt128;
    pub fun getTransactionData(user: [UInt8], nonce: UInt128): ERC6358Protocol.OmniverseTxData;
}
